UniversityManagementSystem/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Newtonsoft.Json;
using UniversityManagementSystem.Models;
using UniversityManagementSystem.Models.ViewModel;

namespace UniversityManagementSystem.Controllers
{
    public class CourseController : Controller
    {
        ProjectDbContext db = new ProjectDbContext();
        public ActionResult Save()
        {
            List<Department> getAllDepartments = db.Departments.ToList();
            List<Semester> getAllSemesters = db.Semesters.ToList();
            ViewBag.getAllDepartments = getAllDepartments;
            ViewBag.getAllSemesters = getAllSemesters;
            return View();
        }
        public JsonResult IsValidCode(string Code)
        {
            return Json(!db.Courses.Any(course => course.Code == Code), JsonRequestBehavior.AllowGet);
        }
        public JsonResult IsValidName(string Name)
        {
            return Json(!db.Courses.Any(course => course.Name == Name), JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult Save(Course course)
        {
            var result = false;
            try
            {
                if (ModelState.IsValid)
                {
                    Course aCourse = new Course();
                    aCourse.Code = course.Code;
                    aCourse.Name = course.Name;
                    aCourse.Credit = course.Credit;
                    aCourse.Description = course.Description;
                    aCourse.DepartmentId = course.DepartmentId;
                    aCourse.SemesterId = course.SemesterId;
                    db.Courses.Add(aCourse);
                    db.SaveChanges();
                    result = true;
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }

            return Json(result, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetCourseByDepartmentId(Department department)
        {
            db.Configuration.ProxyCreationEnabled = false;
            var course = db.Courses.ToList();
            var courseList = course.Where(a => a.DepartmentId == department.Id).ToList();
            return Json(courseList, JsonRequestBehavior.AllowGet);
        }
        public JsonResult IsAssignCourse(int CourseId)
        {
            return Json(!db.AssignCrouses.Any(course => course.CourseId == CourseId && course.IsUnassign == false), JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetCourseDetailByCourseId(Course course)
        {
            var getAllCourse = db.Courses.ToList();
            var courseDetails = getAllCourse.FirstOrDefault(a => a.Id == course.Id);
            CourseViewModel aCourseViewModel = new CourseViewModel();
            if (courseDetails != null)
            {
                aCourseViewModel.Name = courseDetails.Name;
                aCourseViewModel.Credit = courseDetails.Credit;
            }
            aCourseViewModel.IsAssignCourse = IsAssignCourse(course.Id);
            //string value = string.Empty;
            //value = JsonConvert.SerializeObject(aCourseViewModel, Formatting.Indented, new JsonSerializerSettings
            //{
            //    ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            //});

            return Json(aCourseViewModel, JsonRequestBehavior.AllowGet);
        }
        public ActionResult ViewCourseStatics()
        {
            ViewBag.Departments = db.Departments.ToList();
            return View();
        }
        public JsonResult GetCourseStaticsByDepartmentId(Department department)
        {
            var getCourseByDeptId = (from course in db.Courses
                                     join semester in
                                         db.Semesters on course.SemesterId equals semester.Id
                                     where course.DepartmentId == department.Id
                                     select new
                                     {
                                         Id = course.Id,
                                         Code = course.Code,
                                         Name = course.Name,
                                         SemesterNo = semester.SemesterNo
                                     }).ToList();


            List<CourseStaticsViewModel> aStaticsViewModels = new List<CourseStaticsViewModel>();
            foreach (var data in getCourseByDeptId)
            {
                CourseStaticsViewModel aCourseStaticsViewModel = new CourseStaticsViewModel();
                aCourseStaticsViewModel.Code = data.Code;
                aCourseStaticsViewModel.Name = data.Name;
                aCourseStaticsViewModel.SemesterNo = data.SemesterNo;
                int courseId = data.Id;
                var getTeacher = (from assignCourse in db.AssignCrouses
                                  join teacher in db.Teachers on
                                      assignCourse.TeacherId equals teacher.Id
                                  where assignCourse.CourseId == courseId
                                        && assignCourse.IsUnassign == false
                                  select new
                                  {
                                      Name = teacher.Name
                                  }).SingleOrDefault();
                if (getTeacher != null)
                {
                    string teacherName = getTeacher.Name;
                    if (string.IsNullOrEmpty(teacherName))
                    {
                        aCourseStaticsViewModel.TeacherName = "Not Assigned Yet";
                    }
                    else
                    {
                        aCourseStaticsViewModel.TeacherName = teacherName;
                    }
                }
                else
                {
                    aCourseStaticsViewModel.TeacherName = "Not Assigned Yet";
                }
                aStaticsViewModels.Add(aCourseStaticsViewModel);

            }
            return Json(aStaticsViewModels);
        }
        public ActionResult UnassignAllCourses()
        {
           return View();
        }
        public JsonResult ComfirmUnassignAllCourse()
        {
            var getAllAssignCourse = db.AssignCrouses.Where(x => x.IsUnassign == false).ToList();
            foreach (var data in getAllAssignCourse)
            {
                data.IsUnassign = true;
                db.SaveChanges();
            }
            return Json(true , JsonRequestBehavior.AllowGet);
        }
    }
}

UniversityManagementSystem/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web.Mvc;
using UniversityManagementSystem.Models;

namespace UniversityManagementSystem.Controllers
{
    public class StudentController : Controller
    {
        ProjectDbContext db = new ProjectDbContext();
        public ActionResult Save()
        {
            var getAllDepartments = db.Departments.ToList();
            ViewBag.getAllDepartments = getAllDepartments;
            return View();
        }
        public JsonResult IsEmailExist(string Email)
        {
            return Json(!db.Students.Any(stu => stu.Email == Email), JsonRequestBehavior.AllowGet);
        }
        public JsonResult SaveStudent(Student student)
        {
            string regNo = "";
            try
            {
                if (ModelState.IsValid)
                {
                    Student aStudent = new Student();
                    aStudent.Name = student.Name;
                    aStudent.Email = student.Email;
                    aStudent.ContactNo = student.ContactNo;
                    aStudent.Date = student.Date.Date;
                    aStudent.Address = student.Address;
                    aStudent.DepartmentId = student.DepartmentId;
                    aStudent.RegNo = GenerateRegNo(student.DepartmentId, student.Date);
                    regNo = aStudent.RegNo;
                    db.Students.Add(aStudent);
                    db.SaveChanges();
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return Json(regNo, JsonRequestBehavior.AllowGet);
        }
        public string GenerateRegNo(int deptId, DateTime date)
        {
            var dept = db.Departments.FirstOrDefault(x => x.Id == deptId);
            string regNo = "";
            if (dept != null)
            {
                var code = dept.Code;
                var year = date.Date.Year.ToString();
                string codeYear = code + "-" + year;
                var stu = db.Students.Where(x => x.RegNo.Contains(codeYear)).ToList();
                if (stu.Count > 0)
                {
                    var stuReg = stu.Last();
                    string reg = stuReg.RegNo;
                    string[] numbers = Regex.Split(reg, @"\D+");
                    string value = numbers.Last();

                    if (!string.IsNullOrEmpty(value))
                    {
                        int counter = int.Parse(value);
                        int i = ++counter;
                        regNo = codeYear + "-" + i.ToString("000");
                    }
                }
                else
                {
                    int counter = 0;
                    regNo = codeYear + "-" + (++counter).ToString("000");
                }
            }
            return regNo;
        }
        public ActionResult EnrollInACourse()
        {
            var getAllStudents = db.Students.ToList();
            ViewBag.getAllStudents = getAllStudents;
            return View();
        }
        public JsonResult IsEnrolledCourse(CourseEnroll courseEnroll)
        {
            return Json(!db.CourseEnrolls.Any(course => course.CourseId == courseEnroll.CourseId && course.StudentId == courseEnroll.StudentId), JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetStudentInfoByStudentId(Student student)
        {
            var getAllstudent = db.Students.ToList();
            var studentDetails = getAllstudent.FirstOrDefault(a => a.Id == student.Id);
            CourseEnroll aCourseEnroll = new CourseEnroll();
            int deptId;
            if (studentDetails != null)
            {
                aCourseEnroll.Name = studentDetails.Name;
                aCourseEnroll.Email = studentDetails.Email;
                deptId = studentDetails.DepartmentId;
                var department = db.Departments.FirstOrDefault(x => x.Id == deptId);
                if (department != null) aCourseEnroll.Department = department.Name;
            }
            //string value = string.Empty;
            //value = JsonConvert.SerializeObject(takenAndRemainingCredit, Formatting.Indented, new JsonSerializerSettings
            //{
            //    ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            //});
            return Json(aCourseEnroll, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetCourseByStudentDepartment(Student student)
        {
            var studentDetails = db.Students.FirstOrDefault(a => a.Id == student.Id);
            db.Configuration.ProxyCreationEnabled = false;
            var course = db.Courses.ToList();
            var courseList = course.Where(a => studentDetails != null && a.DepartmentId == studentDetails.DepartmentId).ToList();

            return Json(courseList, JsonRequestBehavior.AllowGet);
        }
        public JsonResult SaveCourseEnrollInfo(CourseEnroll courseEnroll)
        {
            bool result = false;
            try
            {
                if (ModelState.IsValid)
                {
                    CourseEnroll aCourseEnroll = new CourseEnroll();
                    aCourseEnroll.StudentId = courseEnroll.StudentId;
                    aCourseEnroll.CourseId = courseEnroll.CourseId;
                    aCourseEnroll.Date = courseEnroll.Date.Date;
                    db.CourseEnrolls.Add(aCourseEnroll);
                    db.SaveChanges();
                    result = true;
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        public ActionResult SaveResult()
        {
            var getAllStudents = db.Students.ToList();
            ViewBag.getAllStudents = getAllStudents;
            var getAllGradeLetter = db.Grades.ToList();
            ViewBag.getAllGradeLetter = getAllGradeLetter;
            return View();
        }
        public JsonResult GetStudentEnrollCourses(Student student)
        {
            var studentEnrollCourse = (from enrollCourse in db.CourseEnrolls
                                       join courseN in db.Courses on enrollCourse.CourseId equals courseN.Id
                                       where enrollCourse.StudentId == student.Id
                                       select new
                                       {
                                           Id = courseN.Id,
                                           Name = courseN.Name
                                       }).ToList();
            return Json(studentEnrollCourse, JsonRequestBehavior.AllowGet);
        }
        public JsonResult SaveStudentResult(StudentResult studentResult)
        {
            string result = "";
            try
            {
                if (ModelState.IsValid)
                {
                    StudentResult aResult = new StudentResult();
                    aResult.StudentId = studentResult.StudentId;
                    aResult.CourseId = studentResult.CourseId;
                    aResult.GradeId = studentResult.GradeId;
                    var alreadySaveResult = db.StudentResults.FirstOrDefault(x => x.StudentId == studentResult.StudentId && x.CourseId == studentResult.CourseId);
                    if (alreadySaveResult == null)
                    {
                        db.StudentResults.Add(aResult);
                        db.SaveChanges();
                        result = "Successfully! Save Student Result";
                    }
                    else
                    {
                        alreadySaveResult.GradeId = studentResult.GradeId;
                        db.SaveChanges();
                        result = "Successfully! Update Student Result";
                    }
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        public ActionResult ViewResult()
        {
            var getAllStudents = db.Students.ToList();
            ViewBag.getAllStudents = getAllStudents;
            return View();
        }
        public JsonResult GetResultByStudentId(Student student)
        {
            var studentEnrollCourseByStudentId = (from enrollCourse in db.CourseEnrolls
                                                  join courseN in db.Courses on enrollCourse.CourseId equals courseN.Id
                                                  where enrollCourse.StudentId == student.Id
                                                  select new
                                                  {
                                                      Id = courseN.Id,
                                                      Code = courseN.Code,
                                                      Name = courseN.Name
                                                  }).ToList();

            List<StudentResultViewModel> aResultViewModels = new List<StudentResultViewModel>();
            foreach (var data in studentEnrollCourseByStudentId)
            {
                StudentResultViewModel resultViewModel = new StudentResultViewModel();
                resultViewModel.CourseCode = data.Code;
                resultViewModel.Name = data.Name;
                int courseId = data.Id;
                var gradeLetterFind = (from studentR in db.StudentResults
                                       join gradeLetter in db.Grades on studentR.GradeId equals gradeLetter.Id
                                       where studentR.StudentId == student.Id && studentR.CourseId == courseId

UniversityManagementSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title - University</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/custom.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.min.css" rel="stylesheet"/>
    <link href="~/Content/jquery-ui.css" rel="stylesheet" />
</head>
<body class="nav-md">
    <div class="container body">
        <div class="main_container">
            <div class="col-md-3 left_col">
                <div class="left_col scroll-view">
                    <div class="navbar nav_title" style="border: 0;">
                        <a href="#" class="site_title"><i class="fa fa-paw"></i> <span>BITM</span></a>
                    </div>

                    <div class="clearfix"></div>
                    <!-- menu profile quick info -->
                    @*<div class="profile clearfix">
                            <div class="profile_pic">
                                 <img src="tofael.jpg" alt="..." class="img-circle profile_img">
                            </div>
                              <div class="profile_info">
                               <span>Welcome,</span>
                               <h2>Md, Tofael</h2>
                             </div>
                        </div>*@
                    <!-- /menu profile quick info -->
                    <br />

                    <!-- sidebar menu -->
                    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                        <div class="menu_section">
                            <ul class="nav side-menu">
                                <li><a href="@Url.Action("Index","Home")"><i class="fa fa-home"></i> Home </a> </li>
                                <li>
                                    <a><i class="fa fa-institution"></i> Department <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu">
                                        <li><a href="@Url.Action("SaveNewDept","Department")">Add New Department</a></li>
                                        <li><a href="@Url.Action("ShowAllDept","Department")">Department List</a></li>
                                    </ul>
                                </li>
                                <li>
                                    <a><i class="fa fa-clone"></i> Course <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu">
                                        <li><a href="@Url.Action("Save","Course")">Add New Course</a></li>
                                        <li><a href="@Url.Action("ViewCourseStatics","Course")">View Course Statics</a></li>
                                    </ul>
                                </li>
                                <li>
                                    <a><i class="fa fa-newspaper-o"></i> Teacher <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu">
                                        <li><a href="@Url.Action("Save","Teacher")">Add New Teacher</a></li>
                                        <li><a href="@Url.Action("CourseAssign","Teacher")">Course Assign</a></li>
                                    </ul>
                                </li>
                                <li>
                                    <a><i class="fa fa-group"></i> Student <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu">
                                        <li><a href="@Url.Action("Save","Student")">Registration</a></li>
                                        <li><a href="@Url.Action("EnrollInACourse","Student")">Enroll Course</a></li>
                                        <li><a href="@Url.Action("SaveResult","Student")">Save Result</a></li>
                                        <li><a href="@Url.Action("ViewResult","Student")">View Result</a></li>
                                    </ul>
                                </li>
                                <li>
                                    <a><i class="fa fa-odnoklassniki-square"></i>Class Room <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu">
                                        <li><a href="@Url.Action("Index","ManageClassRoom")">Allocate Classrooms</a></li>
                                        <li><a href="@Url.Action("ViewClassSchedule","ManageClassRoom")">View Class Schedule</a></li>
                                    </ul>
                                </li>
                                <li><a href="@Url.Action("UnassignAllCourses","Course")"><i class="fa fa-exclamation-triangle"></i>Unasign All Course</a> </li>
                                <li><a href="@Url.Action("UnallocateAllClassRoom","ManageClassRoom")"><i class="fa fa-exclamation-circle"></i>Unalocate All Classrooms</a> </li>
                            </ul>
                        </div>

                    </div>
                    <!-- /sidebar menu -->
                    <!-- /menu footer buttons -->
                    <div class="sidebar-footer hidden-small">
                        <a data-toggle="tooltip" data-placement="top" title="Settings">
                            <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
                        </a>
                        <a data-toggle="tooltip" data-placement="top" title="FullScreen">
                            <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
                        </a>
                        <a data-toggle="tooltip" data-placement="top" title="Lock">
                            <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
                        </a>
                        <a data-toggle="tooltip" data-placement="top" title="Logout" href="#">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
                        </a>
                    </div>
                    <!-- /menu footer buttons -->
                </div>
            </div>
            <!-- top navigation -->
            <div class="top_nav">
                <div class="nav_menu">
                    <nav>
                        <div class="nav toggle">
                            <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                        </div>

                        <ul class="nav navbar-nav navbar-right">
                            <li class="">
                                <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                    @*<img src="" alt="">*@Tofael
                                    <span class=" fa fa-angle-down"></span>
                                </a>
                                <ul class="dropdown-menu dropdown-usermenu pull-right">
                                    <li><a href="#"> Profile</a></li>
                                    <li><a href="#"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
                                </ul>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>

            <div class="right_col" role="main" style="min-height: 1381px;">
                @RenderBody()

            </div>
            <div class="footer_fixed">
                <footer>
                    <div class="pull-right">
                        &copy; @DateTime.Now.Year - Fighter Team
                    </div>
                    <div class="clearfix"></div>
                </footer>
            </div>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/jquery-ui.js"></script>
    <script src="~/Scripts/bootstrap-progressbar.min.js"></script>
    <script src="~/Scripts/custom.min.js"></script>
    <script src="~/Scripts/sweetalert2.all.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/promise-polyfill"></script>
    @RenderSection("scripts", required: false)
</body>
</html>